# Generated by Django 4.1.7 on 2023-05-05 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=1000)),
                ('ingredients', models.CharField(max_length=1000)),
                ('recipe_id', models.CharField(max_length=3, unique=True)),
                ('display_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeManager.recipecategory')),
            ],
        ),
    ]
