# Generated by Django 4.1.7 on 2023-05-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeentry',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
